spring:
  data:
    mongodb:
      username: ghada
      password: 1234
      host: 192.168.56.102
      port: 27017
      database: customer
      authentication-database: admin


server:
  port: 8090