server:
  port: 8040
spring:
  data:
    mongodb:
      username: ghada
      password: 1234
      host: 192.168.56.102
      port: 27017
      database: notification
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: 192.168.56.102:9092
      group-id: orderGroup,paymentGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: OrderConfirmation:com.micro.notificationservice.kafka.OrderConfirmation,paymentConfirmation:com.micro.notificationservice.kafka.PaymentConfirmation
  mail:
    host: 192.168.56.102
    port: 1025
    username: ghada
    password: 1234
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000