spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderEcommerce?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8082

application:
  config:
    customer-url: http://localhost:8090/api/v1/customers
    product-url: http://localhost:8097/api/v1/products
    payment-url: http://localhost:8060/api/v1/payments

  kafka:
    producer:
      bootstrap-servers: 192.168.56.102:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: OrderConfirmation:com.micro.orderservice.kafka.OrderConfirmation

