spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://192.168.56.102:9095/realms/eCommerce"
  application:
    name: gatewayService
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8088
